<definitions 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:tns="tp.serviceweb"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns="http://schemas.xmlsoap.org/wsdl/"
targetNamespace="tp.serviceweb"
name="EnArDescriptorService">

    <message name="EnArDescriptorRequest">
        <part name="word" type="xsd:string"></part>
    </message>
    <message name="EnArDescriptorResponse">
        <part name="description" type="xsd:string"></part>
    </message>
    <message name="FaultMessage">
        <part name="description" type="xsd:string" />
    </message>

    <portType name="describeArabic">
        <operation name="describeArabic">
            <input message="tns:EnArDescriptorRequest"></input>
            <output message="tns:EnArDescriptorResponse"></output>
            <fault name="wordNotFound" message="FaultMessage"/>
        </operation>
    </portType>

    <binding name="EnArDescriptorPortBinding" type="tns:describeArabic">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="describeArabic">
            <soap:operation soapAction="describeArabic"></soap:operation>
            <input>
                <soap:body use="literal" namespace="tp.serviceweb"/>
            </input>
            <output>
                <soap:body use="literal" namespace="tp.serviceweb"/>
            </output>
            <fault>
                <soap:body use="literal" namespace="tp.serviceweb"/>
            </fault>
        </operation>
    </binding>

    <service name="EnArDescriptorService">
        <port name="EnArDescriptorPort" binding="tns:EnArDescriptorPortBinding">
            <soap:address location="http://localhost:8000/index.php"></soap:address>
        </port>
    </service>
</definitions>